import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.styles'
import { Navbar,Hero,TopServices,WhyUs,Footer } from '../components';
export default function Home() {
  return (
    <div className="min-h-[100vh] min-w-[100vw]">
      <Head>
        <title>Segalabersih.id - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full min-h-[100vh] overflow-hidden bg-primary">
          <div className={`${styles.paddingX} ${styles.flexCenter}`}>
            <div className={`${styles.boxWidth}`}>
              <Navbar />
            </div>
          </div>
          <div className={`bg-primary ${styles.flexStart}`}>
            <div className={`${styles.boxWidth}`}>
              <Hero />
            </div>
          </div>
          <div className={`bg-primary`}>
            <div className={`${styles.boxWidth}`}>
            <WhyUs />
            <TopServices />
            </div>
          </div>
      </main>
    </div>
  )
}
